// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: clinic_auth.sql

package db

import (
	"context"
	"database/sql"
)

const getClinicByEmail = `-- name: GetClinicByEmail :one
SELECT id, first_name, last_name, clinic_name, email, password, open_time, close_time, description, created_at FROM clinics
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetClinicByEmail(ctx context.Context, email sql.NullString) (Clinic, error) {
	row := q.db.QueryRowContext(ctx, getClinicByEmail, email)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.ClinicName,
		&i.Email,
		&i.Password,
		&i.OpenTime,
		&i.CloseTime,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const updateClinic = `-- name: UpdateClinic :one
UPDATE clinics
SET
    first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    clinic_name = COALESCE($4, clinic_name),
    email = COALESCE($5, email),
    password = COALESCE($6, password),
    open_time = COALESCE($7, open_time),
    close_time = COALESCE($8, close_time),
    description = COALESCE($9, description)
WHERE
    id = $1
RETURNING id, first_name, last_name, clinic_name, email, password, open_time, close_time, description, created_at
`

type UpdateClinicParams struct {
	ID          int64          `json:"id"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	ClinicName  sql.NullString `json:"clinic_name"`
	Email       sql.NullString `json:"email"`
	Password    sql.NullString `json:"password"`
	OpenTime    sql.NullTime   `json:"open_time"`
	CloseTime   sql.NullTime   `json:"close_time"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateClinic(ctx context.Context, arg UpdateClinicParams) (Clinic, error) {
	row := q.db.QueryRowContext(ctx, updateClinic,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.ClinicName,
		arg.Email,
		arg.Password,
		arg.OpenTime,
		arg.CloseTime,
		arg.Description,
	)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.ClinicName,
		&i.Email,
		&i.Password,
		&i.OpenTime,
		&i.CloseTime,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
